version: '3'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      S3_BUCKET_NAME: jiren-bucket
      AWS_ACCESS_KEY_ID: AKIA3JBG5QLHQH3U2UUN
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: us-east-1
      JWT_SECRET: saborcito
      SENDGRID_API_KEY: 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
      SENDGRID_EMAIL: ed.aws.reservas@gmail.com
      HOST_FRONTEND: http://tu-reserva.com
      SQL_HOST: database-1.cdbzwdqhzgmc.us-east-1.rds.amazonaws.com
      SQL_USER: jiren
      SQL_PASSWORD: saborcito
      SQL_DATABASE: database-1
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
