name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # o el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: reservation
          environment_name: nombre-de-tu-entorno
          version_label: ${{ github.run_id }}
          region: us-east-1 # o tu región de AWS
          deployment_package: deployment.zip
